-- Phase 6A-2-2: Work / Item基盤のみ。既存履歴からの自動生成・補完なし。
-- 適用先DB・search_pathを確認し、同一セッションで全体を実行する。
-- エラー時は停止してROLLBACK。psqlでは -v ON_ERROR_STOP=1 を使用する。
-- DEFAULTなし（PKはIDENTITY）。削除cascadeなし。UNIQUEのindex以外は追加しない。
BEGIN;

CREATE TABLE t_process_work (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    process_history_id bigint NOT NULL,
    bridge_type varchar(32) NOT NULL,
    bridge_model varchar(255),
    requires_stud_hole_expansion boolean NOT NULL,
    tuner_model varchar(255) NOT NULL,
    tuner_mounting_type varchar(32) NOT NULL,
    tuner_bush_required boolean NOT NULL,
    tuner_layout varchar(32) NOT NULL,
    pickup_layout varchar(255) NOT NULL,
    selector_positions integer NOT NULL,
    control_layout varchar(255) NOT NULL,
    jack_mounting_type varchar(32) NOT NULL,
    string_maker varchar(150),
    string_model varchar(255) NOT NULL,
    string_gauge varchar(100) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT pk_process_work PRIMARY KEY (id),
    CONSTRAINT fk_process_work_process_history FOREIGN KEY (process_history_id) REFERENCES t_process_history(id),
    CONSTRAINT uk_process_work_process_history UNIQUE (process_history_id),
    CONSTRAINT ck_process_work_bridge_type CHECK (bridge_type IN ('SIX_POINT', 'TWO_POINT', 'FLOYD_ROSE')),
    CONSTRAINT ck_process_work_tuner_mounting_type CHECK (tuner_mounting_type IN ('PRESS_BUSHING', 'NUT_FASTENING')),
    CONSTRAINT ck_process_work_tuner_layout CHECK (tuner_layout IN ('SIX_IN_LINE')),
    CONSTRAINT ck_process_work_jack_mounting_type CHECK (jack_mounting_type IN ('BOAT_PLATE'))
);

CREATE TABLE t_process_work_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    process_work_id bigint NOT NULL,
    item_key varchar(64) NOT NULL,
    item_order integer NOT NULL,
    status varchar(32) NOT NULL,
    completed_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    CONSTRAINT pk_process_work_item PRIMARY KEY (id),
    CONSTRAINT fk_process_work_item_process_work FOREIGN KEY (process_work_id) REFERENCES t_process_work(id),
    CONSTRAINT uk_process_work_item_work_key UNIQUE (process_work_id, item_key),
    CONSTRAINT uk_process_work_item_work_order UNIQUE (process_work_id, item_order),
    CONSTRAINT ck_process_work_item_item_key CHECK (item_key IN ('BRIDGE_SIX_POINT_INSTALL', 'BRIDGE_MOVEMENT_CHECK', 'STUD_HOLE_EXPANSION', 'STUD_INSTALL', 'BRIDGE_TWO_POINT_INSTALL', 'SPRING_HANGER_INSTALL', 'PICKGUARD_INSTALL', 'JACK_PLATE_INSTALL', 'JACK_WIRING', 'GROUND_WIRING', 'ELECTRONICS_SOUND_CHECK', 'ELECTRONICS_PARTS_CHECK', 'ELECTRONICS_FINAL_FASTENING', 'TUNER_BUSHING_INSTALL', 'TUNER_INSTALL', 'STRING_INSTALL')),
    CONSTRAINT ck_process_work_item_status CHECK (status IN ('NOT_STARTED', 'COMPLETED')),
    CONSTRAINT ck_process_work_item_order CHECK (item_order > 0),
    CONSTRAINT ck_process_work_item_status_completed_at CHECK ((status = 'NOT_STARTED' AND completed_at IS NULL) OR (status = 'COMPLETED' AND completed_at IS NOT NULL))
);

COMMIT;
