-- Phase 6A-1-1: 製品マスタの任意拡張。既存ProductへのINSERT/UPDATEなし。
-- 仕様列は全てNULL許可・DEFAULTなし。未設定をfalseや推測値で補完しない。
-- 型番/表示仕様は既存Productの255文字に合わせる。メーカー名150、ゲージ100。
-- Enumコードは32文字。製品FKのUNIQUEが検索用indexを兼ねるため追加index不要。
BEGIN;

CREATE TABLE m_product_parts_spec (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    bridge_type varchar(32),
    bridge_model varchar(255),
    requires_stud_hole_expansion boolean,
    tuner_model varchar(255),
    tuner_mounting_type varchar(32),
    tuner_bush_required boolean,
    tuner_layout varchar(32),
    selector_positions integer,
    control_layout varchar(255),
    jack_mounting_type varchar(32),
    string_maker varchar(150),
    string_model varchar(255),
    string_gauge varchar(100),
    CONSTRAINT pk_product_parts_spec PRIMARY KEY (id),
    CONSTRAINT uk_product_parts_spec_product UNIQUE (product_id),
    CONSTRAINT fk_product_parts_spec_product FOREIGN KEY (product_id) REFERENCES m_product(id),
    CONSTRAINT ck_product_parts_spec_bridge_type CHECK (bridge_type IN ('SIX_POINT', 'TWO_POINT', 'FLOYD_ROSE')),
    CONSTRAINT ck_product_parts_spec_tuner_mounting_type CHECK (tuner_mounting_type IN ('PRESS_BUSHING', 'NUT_FASTENING')),
    CONSTRAINT ck_product_parts_spec_tuner_layout CHECK (tuner_layout IN ('SIX_IN_LINE')),
    CONSTRAINT ck_product_parts_spec_jack_mounting_type CHECK (jack_mounting_type IN ('BOAT_PLATE'))
);

COMMIT;
